# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Internationalization
spring.messages.basename=messages/messages

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h

management:
endpoints:
web:
exposure:
include: "health,info,prometheus"
metrics:
tags: "petclinic-tag"
application: ${spring.application.name}
spring:
application:
name: petclinic

otel:
exporter:
otlp:
endpoint: https://tempo.observability.svc.cluster.local:4318 # Adress till Tempo OTLP HTTP-mottagare (anpassa vid behov)
# endpoint: https://tempo.observability.svc.cluster.local:4317 # För gRPC
service:
name: ${spring.application.name} # *** Använder nu "petclinic" via variabeln ***
# traces:
# sampler:
# probability: 1.0 # Skicka alla traces under labben